// Bundles the plugin (our src + shared browser-client modules) into ONE
// file Vencord's own esbuild can compile as a userplugin. Vencord-provided
// modules stay external (Vencord resolves them at ITS build time).
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))

await build({
    entryPoints: [path.join(here, '../src/index.ts')],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    outfile: path.join(here, '../dist/grammarForge/index.ts'),
    alias: { '@': path.join(here, '../../browser/src') },
    external: ['@utils/*', '@api/*', '@webpack', '@webpack/common'],
    banner: {
        js: '// GrammarForge Vencord plugin — GENERATED by clients/vencord/scripts/build.mjs. Do not edit here; edit clients/vencord/src in the grammar-forge repo.',
    },
    logLevel: 'info',
})
