// Vendored from LanguageTool upstream:
//   https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-core/src/main/proto/ml_server.proto
// Retrieved 2026-06-07. Regenerate bindings with `task -d bridge proto`; do
// not hand-edit. Provenance comment is the only divergence from upstream.
//
// GrammarForge implements `MLServer.Match` against this proto. The service
// lives in internal/ltgrpc; the generated bindings are in internal/ltgrpc/pb.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ml_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessingServer_Analyze_FullMethodName = "/lt_ml_server.ProcessingServer/Analyze"
	ProcessingServer_Process_FullMethodName = "/lt_ml_server.ProcessingServer/Process"
)

// ProcessingServerClient is the client API for ProcessingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessingServerClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type processingServerClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingServerClient(cc grpc.ClientConnInterface) ProcessingServerClient {
	return &processingServerClient{cc}
}

func (c *processingServerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, ProcessingServer_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingServerClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, ProcessingServer_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServerServer is the server API for ProcessingServer service.
// All implementations must embed UnimplementedProcessingServerServer
// for forward compatibility.
type ProcessingServerServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedProcessingServerServer()
}

// UnimplementedProcessingServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessingServerServer struct{}

func (UnimplementedProcessingServerServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedProcessingServerServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedProcessingServerServer) mustEmbedUnimplementedProcessingServerServer() {}
func (UnimplementedProcessingServerServer) testEmbeddedByValue()                          {}

// UnsafeProcessingServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingServerServer will
// result in compilation errors.
type UnsafeProcessingServerServer interface {
	mustEmbedUnimplementedProcessingServerServer()
}

func RegisterProcessingServerServer(s grpc.ServiceRegistrar, srv ProcessingServerServer) {
	// If the following call panics, it indicates UnimplementedProcessingServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessingServer_ServiceDesc, srv)
}

func _ProcessingServer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessingServer_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessingServer_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServerServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessingServer_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServerServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessingServer_ServiceDesc is the grpc.ServiceDesc for ProcessingServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessingServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lt_ml_server.ProcessingServer",
	HandlerType: (*ProcessingServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _ProcessingServer_Analyze_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _ProcessingServer_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_server.proto",
}

const (
	MLServer_Match_FullMethodName         = "/lt_ml_server.MLServer/Match"
	MLServer_MatchAnalyzed_FullMethodName = "/lt_ml_server.MLServer/MatchAnalyzed"
)

// MLServerClient is the client API for MLServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLServerClient interface {
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	MatchAnalyzed(ctx context.Context, in *AnalyzedMatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
}

type mLServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServerClient(cc grpc.ClientConnInterface) MLServerClient {
	return &mLServerClient{cc}
}

func (c *mLServerClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, MLServer_Match_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServerClient) MatchAnalyzed(ctx context.Context, in *AnalyzedMatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, MLServer_MatchAnalyzed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServerServer is the server API for MLServer service.
// All implementations must embed UnimplementedMLServerServer
// for forward compatibility.
type MLServerServer interface {
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	MatchAnalyzed(context.Context, *AnalyzedMatchRequest) (*MatchResponse, error)
	mustEmbedUnimplementedMLServerServer()
}

// UnimplementedMLServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLServerServer struct{}

func (UnimplementedMLServerServer) Match(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Match not implemented")
}
func (UnimplementedMLServerServer) MatchAnalyzed(context.Context, *AnalyzedMatchRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchAnalyzed not implemented")
}
func (UnimplementedMLServerServer) mustEmbedUnimplementedMLServerServer() {}
func (UnimplementedMLServerServer) testEmbeddedByValue()                  {}

// UnsafeMLServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServerServer will
// result in compilation errors.
type UnsafeMLServerServer interface {
	mustEmbedUnimplementedMLServerServer()
}

func RegisterMLServerServer(s grpc.ServiceRegistrar, srv MLServerServer) {
	// If the following call panics, it indicates UnimplementedMLServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLServer_ServiceDesc, srv)
}

func _MLServer_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServerServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLServer_Match_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServerServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLServer_MatchAnalyzed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzedMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServerServer).MatchAnalyzed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLServer_MatchAnalyzed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServerServer).MatchAnalyzed(ctx, req.(*AnalyzedMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLServer_ServiceDesc is the grpc.ServiceDesc for MLServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lt_ml_server.MLServer",
	HandlerType: (*MLServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Match",
			Handler:    _MLServer_Match_Handler,
		},
		{
			MethodName: "MatchAnalyzed",
			Handler:    _MLServer_MatchAnalyzed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_server.proto",
}

const (
	PostProcessingServer_Process_FullMethodName = "/lt_ml_server.PostProcessingServer/Process"
)

// PostProcessingServerClient is the client API for PostProcessingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// for e.g. resorting suggestions
type PostProcessingServerClient interface {
	Process(ctx context.Context, in *PostProcessingRequest, opts ...grpc.CallOption) (*MatchResponse, error)
}

type postProcessingServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPostProcessingServerClient(cc grpc.ClientConnInterface) PostProcessingServerClient {
	return &postProcessingServerClient{cc}
}

func (c *postProcessingServerClient) Process(ctx context.Context, in *PostProcessingRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, PostProcessingServer_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostProcessingServerServer is the server API for PostProcessingServer service.
// All implementations must embed UnimplementedPostProcessingServerServer
// for forward compatibility.
//
// for e.g. resorting suggestions
type PostProcessingServerServer interface {
	Process(context.Context, *PostProcessingRequest) (*MatchResponse, error)
	mustEmbedUnimplementedPostProcessingServerServer()
}

// UnimplementedPostProcessingServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostProcessingServerServer struct{}

func (UnimplementedPostProcessingServerServer) Process(context.Context, *PostProcessingRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedPostProcessingServerServer) mustEmbedUnimplementedPostProcessingServerServer() {}
func (UnimplementedPostProcessingServerServer) testEmbeddedByValue()                              {}

// UnsafePostProcessingServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostProcessingServerServer will
// result in compilation errors.
type UnsafePostProcessingServerServer interface {
	mustEmbedUnimplementedPostProcessingServerServer()
}

func RegisterPostProcessingServerServer(s grpc.ServiceRegistrar, srv PostProcessingServerServer) {
	// If the following call panics, it indicates UnimplementedPostProcessingServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostProcessingServer_ServiceDesc, srv)
}

func _PostProcessingServer_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostProcessingServerServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostProcessingServer_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostProcessingServerServer).Process(ctx, req.(*PostProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostProcessingServer_ServiceDesc is the grpc.ServiceDesc for PostProcessingServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostProcessingServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lt_ml_server.PostProcessingServer",
	HandlerType: (*PostProcessingServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _PostProcessingServer_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_server.proto",
}
