// Vendored from LanguageTool upstream:
//   https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-core/src/main/proto/ml_server.proto
// Retrieved 2026-06-07. Regenerate bindings with `task -d bridge proto`; do
// not hand-edit. Provenance comment is the only divergence from upstream.
//
// GrammarForge implements `MLServer.Match` against this proto. The service
// lives in internal/ltgrpc; the generated bindings are in internal/ltgrpc/pb.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ml_server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessingOptions_Level int32

const (
	ProcessingOptions_picky        ProcessingOptions_Level = 0
	ProcessingOptions_academic     ProcessingOptions_Level = 1
	ProcessingOptions_clarity      ProcessingOptions_Level = 2
	ProcessingOptions_professional ProcessingOptions_Level = 3
	ProcessingOptions_creative     ProcessingOptions_Level = 4
	ProcessingOptions_customer     ProcessingOptions_Level = 5
	ProcessingOptions_jobapp       ProcessingOptions_Level = 6
	ProcessingOptions_objective    ProcessingOptions_Level = 7
	ProcessingOptions_elegant      ProcessingOptions_Level = 8
	ProcessingOptions_defaultLevel ProcessingOptions_Level = 9
)

// Enum value maps for ProcessingOptions_Level.
var (
	ProcessingOptions_Level_name = map[int32]string{
		0: "picky",
		1: "academic",
		2: "clarity",
		3: "professional",
		4: "creative",
		5: "customer",
		6: "jobapp",
		7: "objective",
		8: "elegant",
		9: "defaultLevel",
	}
	ProcessingOptions_Level_value = map[string]int32{
		"picky":        0,
		"academic":     1,
		"clarity":      2,
		"professional": 3,
		"creative":     4,
		"customer":     5,
		"jobapp":       6,
		"objective":    7,
		"elegant":      8,
		"defaultLevel": 9,
	}
)

func (x ProcessingOptions_Level) Enum() *ProcessingOptions_Level {
	p := new(ProcessingOptions_Level)
	*p = x
	return p
}

func (x ProcessingOptions_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingOptions_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_server_proto_enumTypes[0].Descriptor()
}

func (ProcessingOptions_Level) Type() protoreflect.EnumType {
	return &file_ml_server_proto_enumTypes[0]
}

func (x ProcessingOptions_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingOptions_Level.Descriptor instead.
func (ProcessingOptions_Level) EnumDescriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{1, 0}
}

type Match_MatchType int32

const (
	// * Spelling errors, typically red.
	Match_UnknownWord Match_MatchType = 0
	// * Style errors, typically light blue.
	Match_Hint Match_MatchType = 1
	// * Other errors (including grammar), typically yellow/orange.
	Match_Other Match_MatchType = 2
)

// Enum value maps for Match_MatchType.
var (
	Match_MatchType_name = map[int32]string{
		0: "UnknownWord",
		1: "Hint",
		2: "Other",
	}
	Match_MatchType_value = map[string]int32{
		"UnknownWord": 0,
		"Hint":        1,
		"Other":       2,
	}
)

func (x Match_MatchType) Enum() *Match_MatchType {
	p := new(Match_MatchType)
	*p = x
	return p
}

func (x Match_MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Match_MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_server_proto_enumTypes[1].Descriptor()
}

func (Match_MatchType) Type() protoreflect.EnumType {
	return &file_ml_server_proto_enumTypes[1]
}

func (x Match_MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Match_MatchType.Descriptor instead.
func (Match_MatchType) EnumDescriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{13, 0}
}

type Rule_Tag int32

const (
	Rule_picky        Rule_Tag = 0
	Rule_academic     Rule_Tag = 1
	Rule_clarity      Rule_Tag = 2
	Rule_professional Rule_Tag = 3
	Rule_creative     Rule_Tag = 4
	Rule_customer     Rule_Tag = 5
	Rule_jobapp       Rule_Tag = 6
	Rule_objective    Rule_Tag = 7
	Rule_elegant      Rule_Tag = 8
)

// Enum value maps for Rule_Tag.
var (
	Rule_Tag_name = map[int32]string{
		0: "picky",
		1: "academic",
		2: "clarity",
		3: "professional",
		4: "creative",
		5: "customer",
		6: "jobapp",
		7: "objective",
		8: "elegant",
	}
	Rule_Tag_value = map[string]int32{
		"picky":        0,
		"academic":     1,
		"clarity":      2,
		"professional": 3,
		"creative":     4,
		"customer":     5,
		"jobapp":       6,
		"objective":    7,
		"elegant":      8,
	}
)

func (x Rule_Tag) Enum() *Rule_Tag {
	p := new(Rule_Tag)
	*p = x
	return p
}

func (x Rule_Tag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rule_Tag) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_server_proto_enumTypes[2].Descriptor()
}

func (Rule_Tag) Type() protoreflect.EnumType {
	return &file_ml_server_proto_enumTypes[2]
}

func (x Rule_Tag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rule_Tag.Descriptor instead.
func (Rule_Tag) EnumDescriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{14, 0}
}

type SuggestedReplacement_SuggestionType int32

const (
	SuggestedReplacement_Default     SuggestedReplacement_SuggestionType = 0
	SuggestedReplacement_Translation SuggestedReplacement_SuggestionType = 1
	SuggestedReplacement_Curated     SuggestedReplacement_SuggestionType = 2
)

// Enum value maps for SuggestedReplacement_SuggestionType.
var (
	SuggestedReplacement_SuggestionType_name = map[int32]string{
		0: "Default",
		1: "Translation",
		2: "Curated",
	}
	SuggestedReplacement_SuggestionType_value = map[string]int32{
		"Default":     0,
		"Translation": 1,
		"Curated":     2,
	}
)

func (x SuggestedReplacement_SuggestionType) Enum() *SuggestedReplacement_SuggestionType {
	p := new(SuggestedReplacement_SuggestionType)
	*p = x
	return p
}

func (x SuggestedReplacement_SuggestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuggestedReplacement_SuggestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_server_proto_enumTypes[3].Descriptor()
}

func (SuggestedReplacement_SuggestionType) Type() protoreflect.EnumType {
	return &file_ml_server_proto_enumTypes[3]
}

func (x SuggestedReplacement_SuggestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuggestedReplacement_SuggestionType.Descriptor instead.
func (SuggestedReplacement_SuggestionType) EnumDescriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{16, 0}
}

// NOTE: should this be split this up into different packages?
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_ml_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessingOptions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Language      string                  `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	TempOff       bool                    `protobuf:"varint,2,opt,name=tempOff,proto3" json:"tempOff,omitempty"`
	Level         ProcessingOptions_Level `protobuf:"varint,3,opt,name=level,proto3,enum=lt_ml_server.ProcessingOptions_Level" json:"level,omitempty"`
	Premium       bool                    `protobuf:"varint,4,opt,name=premium,proto3" json:"premium,omitempty"`
	EnabledOnly   bool                    `protobuf:"varint,5,opt,name=enabledOnly,proto3" json:"enabledOnly,omitempty"`
	EnabledRules  []string                `protobuf:"bytes,6,rep,name=enabledRules,proto3" json:"enabledRules,omitempty"`
	DisabledRules []string                `protobuf:"bytes,7,rep,name=disabledRules,proto3" json:"disabledRules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_ml_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessingOptions) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ProcessingOptions) GetTempOff() bool {
	if x != nil {
		return x.TempOff
	}
	return false
}

func (x *ProcessingOptions) GetLevel() ProcessingOptions_Level {
	if x != nil {
		return x.Level
	}
	return ProcessingOptions_picky
}

func (x *ProcessingOptions) GetPremium() bool {
	if x != nil {
		return x.Premium
	}
	return false
}

func (x *ProcessingOptions) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ProcessingOptions) GetEnabledRules() []string {
	if x != nil {
		return x.EnabledRules
	}
	return nil
}

func (x *ProcessingOptions) GetDisabledRules() []string {
	if x != nil {
		return x.DisabledRules
	}
	return nil
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []*AnalyzedSentence    `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_ml_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetSentences() []*AnalyzedSentence {
	if x != nil {
		return x.Sentences
	}
	return nil
}

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []*AnalyzedSentence    `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`
	Options       *ProcessingOptions     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_ml_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessRequest) GetSentences() []*AnalyzedSentence {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *ProcessRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawMatches    []*Match               `protobuf:"bytes,1,rep,name=rawMatches,proto3" json:"rawMatches,omitempty"`
	Matches       []*Match               `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_ml_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessResponse) GetRawMatches() []*Match {
	if x != nil {
		return x.RawMatches
	}
	return nil
}

func (x *ProcessResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type AnalyzedMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []*AnalyzedSentence    `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`
	InputLogging  bool                   `protobuf:"varint,2,opt,name=inputLogging,proto3" json:"inputLogging,omitempty"`          // allow logging of input on error
	TextSessionID []int64                `protobuf:"varint,3,rep,packed,name=textSessionID,proto3" json:"textSessionID,omitempty"` // session ID, for partial rollout & A/B tests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzedMatchRequest) Reset() {
	*x = AnalyzedMatchRequest{}
	mi := &file_ml_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzedMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzedMatchRequest) ProtoMessage() {}

func (x *AnalyzedMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzedMatchRequest.ProtoReflect.Descriptor instead.
func (*AnalyzedMatchRequest) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzedMatchRequest) GetSentences() []*AnalyzedSentence {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *AnalyzedMatchRequest) GetInputLogging() bool {
	if x != nil {
		return x.InputLogging
	}
	return false
}

func (x *AnalyzedMatchRequest) GetTextSessionID() []int64 {
	if x != nil {
		return x.TextSessionID
	}
	return nil
}

type AnalyzedSentence struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Text          string                   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Tokens        []*AnalyzedTokenReadings `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzedSentence) Reset() {
	*x = AnalyzedSentence{}
	mi := &file_ml_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzedSentence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzedSentence) ProtoMessage() {}

func (x *AnalyzedSentence) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzedSentence.ProtoReflect.Descriptor instead.
func (*AnalyzedSentence) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyzedSentence) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzedSentence) GetTokens() []*AnalyzedTokenReadings {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type AnalyzedTokenReadings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*AnalyzedToken       `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	ChunkTags     []string               `protobuf:"bytes,2,rep,name=chunkTags,proto3" json:"chunkTags,omitempty"`
	StartPos      int32                  `protobuf:"varint,3,opt,name=startPos,proto3" json:"startPos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzedTokenReadings) Reset() {
	*x = AnalyzedTokenReadings{}
	mi := &file_ml_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzedTokenReadings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzedTokenReadings) ProtoMessage() {}

func (x *AnalyzedTokenReadings) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzedTokenReadings.ProtoReflect.Descriptor instead.
func (*AnalyzedTokenReadings) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzedTokenReadings) GetReadings() []*AnalyzedToken {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *AnalyzedTokenReadings) GetChunkTags() []string {
	if x != nil {
		return x.ChunkTags
	}
	return nil
}

func (x *AnalyzedTokenReadings) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

type AnalyzedToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PosTag        string                 `protobuf:"bytes,2,opt,name=posTag,proto3" json:"posTag,omitempty"`
	Lemma         string                 `protobuf:"bytes,3,opt,name=lemma,proto3" json:"lemma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzedToken) Reset() {
	*x = AnalyzedToken{}
	mi := &file_ml_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzedToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzedToken) ProtoMessage() {}

func (x *AnalyzedToken) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzedToken.ProtoReflect.Descriptor instead.
func (*AnalyzedToken) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzedToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AnalyzedToken) GetPosTag() string {
	if x != nil {
		return x.PosTag
	}
	return ""
}

func (x *AnalyzedToken) GetLemma() string {
	if x != nil {
		return x.Lemma
	}
	return ""
}

type PostProcessingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []string               `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`                 // input text to be analyzed
	Matches       []*MatchList           `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`                     // matches of input text, to be transformed
	InputLogging  bool                   `protobuf:"varint,3,opt,name=inputLogging,proto3" json:"inputLogging,omitempty"`          // allow logging of input on error
	TextSessionID []int64                `protobuf:"varint,4,rep,packed,name=textSessionID,proto3" json:"textSessionID,omitempty"` // session ID, for partial rollout & A/B tests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostProcessingRequest) Reset() {
	*x = PostProcessingRequest{}
	mi := &file_ml_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostProcessingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostProcessingRequest) ProtoMessage() {}

func (x *PostProcessingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostProcessingRequest.ProtoReflect.Descriptor instead.
func (*PostProcessingRequest) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{9}
}

func (x *PostProcessingRequest) GetSentences() []string {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *PostProcessingRequest) GetMatches() []*MatchList {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *PostProcessingRequest) GetInputLogging() bool {
	if x != nil {
		return x.InputLogging
	}
	return false
}

func (x *PostProcessingRequest) GetTextSessionID() []int64 {
	if x != nil {
		return x.TextSessionID
	}
	return nil
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []string               `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`                 // input text to be analyzed
	InputLogging  bool                   `protobuf:"varint,2,opt,name=inputLogging,proto3" json:"inputLogging,omitempty"`          // allow logging of input on error
	TextSessionID []int64                `protobuf:"varint,3,rep,packed,name=textSessionID,proto3" json:"textSessionID,omitempty"` // session ID, for partial rollout & A/B tests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_ml_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{10}
}

func (x *MatchRequest) GetSentences() []string {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *MatchRequest) GetInputLogging() bool {
	if x != nil {
		return x.InputLogging
	}
	return false
}

func (x *MatchRequest) GetTextSessionID() []int64 {
	if x != nil {
		return x.TextSessionID
	}
	return nil
}

type MatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SentenceMatches []*MatchList           `protobuf:"bytes,1,rep,name=sentenceMatches,proto3" json:"sentenceMatches,omitempty"` // results for each corresponding sentence in MatchRequest (aligned)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_ml_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{11}
}

func (x *MatchResponse) GetSentenceMatches() []*MatchList {
	if x != nil {
		return x.SentenceMatches
	}
	return nil
}

type MatchList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"` // list of matches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchList) Reset() {
	*x = MatchList{}
	mi := &file_ml_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchList) ProtoMessage() {}

func (x *MatchList) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchList.ProtoReflect.Descriptor instead.
func (*MatchList) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{12}
}

func (x *MatchList) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Match struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Offset      uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`           // start position in the sentence (i.e. not relative to whole text)
	Length      uint32                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`           // length of matched area; >0
	Id          string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                    // prefix for rule ids; should use a common value for one model/server
	SubId       string                 `protobuf:"bytes,4,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"` // more specific suffix for rule ids; i.e. one model/server can return multiple values to distinguish between mach types
	Suggestions []string               `protobuf:"bytes,5,rep,name=suggestions,proto3" json:"suggestions,omitempty"`  // legacy; use suggestedReplacements
	// added later, optional (can be substituted by Java)
	RuleDescription       string                  `protobuf:"bytes,6,opt,name=ruleDescription,proto3" json:"ruleDescription,omitempty"`              // description of the rule; can be specific to rule_id + sub_id or shared for all sub_ids of one rule_id
	MatchDescription      string                  `protobuf:"bytes,7,opt,name=matchDescription,proto3" json:"matchDescription,omitempty"`            // description of the match; displayed in e.g. the add-on pop-up
	MatchShortDescription string                  `protobuf:"bytes,8,opt,name=matchShortDescription,proto3" json:"matchShortDescription,omitempty"`  // shortened description of the match; displayed in e.g. LibreOffice context menu
	Url                   string                  `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`                                      // to show a link, e.g. with further explanations for this error
	SuggestedReplacements []*SuggestedReplacement `protobuf:"bytes,10,rep,name=suggestedReplacements,proto3" json:"suggestedReplacements,omitempty"` // new and extended suggestions; overwrite any values set in suggestions
	AutoCorrect           bool                    `protobuf:"varint,11,opt,name=autoCorrect,proto3" json:"autoCorrect,omitempty"`                    // is this correction eligible for auto-correction?
	Type                  Match_MatchType         `protobuf:"varint,12,opt,name=type,proto3,enum=lt_ml_server.Match_MatchType" json:"type,omitempty"`
	ContextForSureMatch   int32                   `protobuf:"zigzag32,13,opt,name=contextForSureMatch,proto3" json:"contextForSureMatch,omitempty"`
	Rule                  *Rule                   `protobuf:"bytes,14,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_ml_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{13}
}

func (x *Match) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Match) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Match) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Match) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *Match) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *Match) GetRuleDescription() string {
	if x != nil {
		return x.RuleDescription
	}
	return ""
}

func (x *Match) GetMatchDescription() string {
	if x != nil {
		return x.MatchDescription
	}
	return ""
}

func (x *Match) GetMatchShortDescription() string {
	if x != nil {
		return x.MatchShortDescription
	}
	return ""
}

func (x *Match) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Match) GetSuggestedReplacements() []*SuggestedReplacement {
	if x != nil {
		return x.SuggestedReplacements
	}
	return nil
}

func (x *Match) GetAutoCorrect() bool {
	if x != nil {
		return x.AutoCorrect
	}
	return false
}

func (x *Match) GetType() Match_MatchType {
	if x != nil {
		return x.Type
	}
	return Match_UnknownWord
}

func (x *Match) GetContextForSureMatch() int32 {
	if x != nil {
		return x.ContextForSureMatch
	}
	return 0
}

func (x *Match) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id, subId, description, url already in Match
	SourceFile string `protobuf:"bytes,1,opt,name=sourceFile,proto3" json:"sourceFile,omitempty"`
	// see http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues
	IssueType     string        `protobuf:"bytes,2,opt,name=issueType,proto3" json:"issueType,omitempty"`
	TempOff       bool          `protobuf:"varint,3,opt,name=tempOff,proto3" json:"tempOff,omitempty"`
	Category      *RuleCategory `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	IsPremium     bool          `protobuf:"varint,5,opt,name=isPremium,proto3" json:"isPremium,omitempty"`
	Tags          []Rule_Tag    `protobuf:"varint,6,rep,packed,name=tags,proto3,enum=lt_ml_server.Rule_Tag" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_ml_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{14}
}

func (x *Rule) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *Rule) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *Rule) GetTempOff() bool {
	if x != nil {
		return x.TempOff
	}
	return false
}

func (x *Rule) GetCategory() *RuleCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Rule) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *Rule) GetTags() []Rule_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RuleCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleCategory) Reset() {
	*x = RuleCategory{}
	mi := &file_ml_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleCategory) ProtoMessage() {}

func (x *RuleCategory) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleCategory.ProtoReflect.Descriptor instead.
func (*RuleCategory) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{15}
}

func (x *RuleCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SuggestedReplacement struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Replacement   string                              `protobuf:"bytes,1,opt,name=replacement,proto3" json:"replacement,omitempty"`
	Description   string                              `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Suffix        string                              `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`           // Value shown in the UI after the replacement (but not part of it).
	Confidence    float32                             `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // from 0 (lowest) to 1 (highest)
	Type          SuggestedReplacement_SuggestionType `protobuf:"varint,5,opt,name=type,proto3,enum=lt_ml_server.SuggestedReplacement_SuggestionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestedReplacement) Reset() {
	*x = SuggestedReplacement{}
	mi := &file_ml_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestedReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedReplacement) ProtoMessage() {}

func (x *SuggestedReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_ml_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedReplacement.ProtoReflect.Descriptor instead.
func (*SuggestedReplacement) Descriptor() ([]byte, []int) {
	return file_ml_server_proto_rawDescGZIP(), []int{16}
}

func (x *SuggestedReplacement) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *SuggestedReplacement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SuggestedReplacement) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *SuggestedReplacement) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SuggestedReplacement) GetType() SuggestedReplacement_SuggestionType {
	if x != nil {
		return x.Type
	}
	return SuggestedReplacement_Default
}

var File_ml_server_proto protoreflect.FileDescriptor

const file_ml_server_proto_rawDesc = "" +
	"\n" +
	"\x0fml_server.proto\x12\flt_ml_server\"_\n" +
	"\x0eAnalyzeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.lt_ml_server.ProcessingOptionsR\aoptions\"\xa4\x03\n" +
	"\x11ProcessingOptions\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x18\n" +
	"\atempOff\x18\x02 \x01(\bR\atempOff\x12;\n" +
	"\x05level\x18\x03 \x01(\x0e2%.lt_ml_server.ProcessingOptions.LevelR\x05level\x12\x18\n" +
	"\apremium\x18\x04 \x01(\bR\apremium\x12 \n" +
	"\venabledOnly\x18\x05 \x01(\bR\venabledOnly\x12\"\n" +
	"\fenabledRules\x18\x06 \x03(\tR\fenabledRules\x12$\n" +
	"\rdisabledRules\x18\a \x03(\tR\rdisabledRules\"\x95\x01\n" +
	"\x05Level\x12\t\n" +
	"\x05picky\x10\x00\x12\f\n" +
	"\bacademic\x10\x01\x12\v\n" +
	"\aclarity\x10\x02\x12\x10\n" +
	"\fprofessional\x10\x03\x12\f\n" +
	"\bcreative\x10\x04\x12\f\n" +
	"\bcustomer\x10\x05\x12\n" +
	"\n" +
	"\x06jobapp\x10\x06\x12\r\n" +
	"\tobjective\x10\a\x12\v\n" +
	"\aelegant\x10\b\x12\x10\n" +
	"\fdefaultLevel\x10\t\"O\n" +
	"\x0fAnalyzeResponse\x12<\n" +
	"\tsentences\x18\x01 \x03(\v2\x1e.lt_ml_server.AnalyzedSentenceR\tsentences\"\x89\x01\n" +
	"\x0eProcessRequest\x12<\n" +
	"\tsentences\x18\x01 \x03(\v2\x1e.lt_ml_server.AnalyzedSentenceR\tsentences\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.lt_ml_server.ProcessingOptionsR\aoptions\"u\n" +
	"\x0fProcessResponse\x123\n" +
	"\n" +
	"rawMatches\x18\x01 \x03(\v2\x13.lt_ml_server.MatchR\n" +
	"rawMatches\x12-\n" +
	"\amatches\x18\x02 \x03(\v2\x13.lt_ml_server.MatchR\amatches\"\x9e\x01\n" +
	"\x14AnalyzedMatchRequest\x12<\n" +
	"\tsentences\x18\x01 \x03(\v2\x1e.lt_ml_server.AnalyzedSentenceR\tsentences\x12\"\n" +
	"\finputLogging\x18\x02 \x01(\bR\finputLogging\x12$\n" +
	"\rtextSessionID\x18\x03 \x03(\x03R\rtextSessionID\"c\n" +
	"\x10AnalyzedSentence\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12;\n" +
	"\x06tokens\x18\x02 \x03(\v2#.lt_ml_server.AnalyzedTokenReadingsR\x06tokens\"\x8a\x01\n" +
	"\x15AnalyzedTokenReadings\x127\n" +
	"\breadings\x18\x01 \x03(\v2\x1b.lt_ml_server.AnalyzedTokenR\breadings\x12\x1c\n" +
	"\tchunkTags\x18\x02 \x03(\tR\tchunkTags\x12\x1a\n" +
	"\bstartPos\x18\x03 \x01(\x05R\bstartPos\"S\n" +
	"\rAnalyzedToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06posTag\x18\x02 \x01(\tR\x06posTag\x12\x14\n" +
	"\x05lemma\x18\x03 \x01(\tR\x05lemma\"\xb2\x01\n" +
	"\x15PostProcessingRequest\x12\x1c\n" +
	"\tsentences\x18\x01 \x03(\tR\tsentences\x121\n" +
	"\amatches\x18\x02 \x03(\v2\x17.lt_ml_server.MatchListR\amatches\x12\"\n" +
	"\finputLogging\x18\x03 \x01(\bR\finputLogging\x12$\n" +
	"\rtextSessionID\x18\x04 \x03(\x03R\rtextSessionID\"v\n" +
	"\fMatchRequest\x12\x1c\n" +
	"\tsentences\x18\x01 \x03(\tR\tsentences\x12\"\n" +
	"\finputLogging\x18\x02 \x01(\bR\finputLogging\x12$\n" +
	"\rtextSessionID\x18\x03 \x03(\x03R\rtextSessionID\"R\n" +
	"\rMatchResponse\x12A\n" +
	"\x0fsentenceMatches\x18\x01 \x03(\v2\x17.lt_ml_server.MatchListR\x0fsentenceMatches\":\n" +
	"\tMatchList\x12-\n" +
	"\amatches\x18\x01 \x03(\v2\x13.lt_ml_server.MatchR\amatches\"\xda\x04\n" +
	"\x05Match\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x15\n" +
	"\x06sub_id\x18\x04 \x01(\tR\x05subId\x12 \n" +
	"\vsuggestions\x18\x05 \x03(\tR\vsuggestions\x12(\n" +
	"\x0fruleDescription\x18\x06 \x01(\tR\x0fruleDescription\x12*\n" +
	"\x10matchDescription\x18\a \x01(\tR\x10matchDescription\x124\n" +
	"\x15matchShortDescription\x18\b \x01(\tR\x15matchShortDescription\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\x12X\n" +
	"\x15suggestedReplacements\x18\n" +
	" \x03(\v2\".lt_ml_server.SuggestedReplacementR\x15suggestedReplacements\x12 \n" +
	"\vautoCorrect\x18\v \x01(\bR\vautoCorrect\x121\n" +
	"\x04type\x18\f \x01(\x0e2\x1d.lt_ml_server.Match.MatchTypeR\x04type\x120\n" +
	"\x13contextForSureMatch\x18\r \x01(\x11R\x13contextForSureMatch\x12&\n" +
	"\x04rule\x18\x0e \x01(\v2\x12.lt_ml_server.RuleR\x04rule\"1\n" +
	"\tMatchType\x12\x0f\n" +
	"\vUnknownWord\x10\x00\x12\b\n" +
	"\x04Hint\x10\x01\x12\t\n" +
	"\x05Other\x10\x02\"\xe4\x02\n" +
	"\x04Rule\x12\x1e\n" +
	"\n" +
	"sourceFile\x18\x01 \x01(\tR\n" +
	"sourceFile\x12\x1c\n" +
	"\tissueType\x18\x02 \x01(\tR\tissueType\x12\x18\n" +
	"\atempOff\x18\x03 \x01(\bR\atempOff\x126\n" +
	"\bcategory\x18\x04 \x01(\v2\x1a.lt_ml_server.RuleCategoryR\bcategory\x12\x1c\n" +
	"\tisPremium\x18\x05 \x01(\bR\tisPremium\x12*\n" +
	"\x04tags\x18\x06 \x03(\x0e2\x16.lt_ml_server.Rule.TagR\x04tags\"\x81\x01\n" +
	"\x03Tag\x12\t\n" +
	"\x05picky\x10\x00\x12\f\n" +
	"\bacademic\x10\x01\x12\v\n" +
	"\aclarity\x10\x02\x12\x10\n" +
	"\fprofessional\x10\x03\x12\f\n" +
	"\bcreative\x10\x04\x12\f\n" +
	"\bcustomer\x10\x05\x12\n" +
	"\n" +
	"\x06jobapp\x10\x06\x12\r\n" +
	"\tobjective\x10\a\x12\v\n" +
	"\aelegant\x10\b\"2\n" +
	"\fRuleCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x02\n" +
	"\x14SuggestedReplacement\x12 \n" +
	"\vreplacement\x18\x01 \x01(\tR\vreplacement\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06suffix\x18\x03 \x01(\tR\x06suffix\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12E\n" +
	"\x04type\x18\x05 \x01(\x0e21.lt_ml_server.SuggestedReplacement.SuggestionTypeR\x04type\";\n" +
	"\x0eSuggestionType\x12\v\n" +
	"\aDefault\x10\x00\x12\x0f\n" +
	"\vTranslation\x10\x01\x12\v\n" +
	"\aCurated\x10\x022\xa6\x01\n" +
	"\x10ProcessingServer\x12H\n" +
	"\aAnalyze\x12\x1c.lt_ml_server.AnalyzeRequest\x1a\x1d.lt_ml_server.AnalyzeResponse\"\x00\x12H\n" +
	"\aProcess\x12\x1c.lt_ml_server.ProcessRequest\x1a\x1d.lt_ml_server.ProcessResponse\"\x002\xa2\x01\n" +
	"\bMLServer\x12B\n" +
	"\x05Match\x12\x1a.lt_ml_server.MatchRequest\x1a\x1b.lt_ml_server.MatchResponse\"\x00\x12R\n" +
	"\rMatchAnalyzed\x12\".lt_ml_server.AnalyzedMatchRequest\x1a\x1b.lt_ml_server.MatchResponse\"\x002e\n" +
	"\x14PostProcessingServer\x12M\n" +
	"\aProcess\x12#.lt_ml_server.PostProcessingRequest\x1a\x1b.lt_ml_server.MatchResponse\"\x00B\x9c\x01\n" +
	"\x10com.lt_ml_serverB\rMlServerProtoP\x01Z1github.com/grammarforge/bridge/internal/ltgrpc/pb\xa2\x02\x03LXX\xaa\x02\n" +
	"LtMlServer\xca\x02\n" +
	"LtMlServer\xe2\x02\x16LtMlServer\\GPBMetadata\xea\x02\n" +
	"LtMlServerb\x06proto3"

var (
	file_ml_server_proto_rawDescOnce sync.Once
	file_ml_server_proto_rawDescData []byte
)

func file_ml_server_proto_rawDescGZIP() []byte {
	file_ml_server_proto_rawDescOnce.Do(func() {
		file_ml_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_server_proto_rawDesc), len(file_ml_server_proto_rawDesc)))
	})
	return file_ml_server_proto_rawDescData
}

var file_ml_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ml_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ml_server_proto_goTypes = []any{
	(ProcessingOptions_Level)(0),             // 0: lt_ml_server.ProcessingOptions.Level
	(Match_MatchType)(0),                     // 1: lt_ml_server.Match.MatchType
	(Rule_Tag)(0),                            // 2: lt_ml_server.Rule.Tag
	(SuggestedReplacement_SuggestionType)(0), // 3: lt_ml_server.SuggestedReplacement.SuggestionType
	(*AnalyzeRequest)(nil),                   // 4: lt_ml_server.AnalyzeRequest
	(*ProcessingOptions)(nil),                // 5: lt_ml_server.ProcessingOptions
	(*AnalyzeResponse)(nil),                  // 6: lt_ml_server.AnalyzeResponse
	(*ProcessRequest)(nil),                   // 7: lt_ml_server.ProcessRequest
	(*ProcessResponse)(nil),                  // 8: lt_ml_server.ProcessResponse
	(*AnalyzedMatchRequest)(nil),             // 9: lt_ml_server.AnalyzedMatchRequest
	(*AnalyzedSentence)(nil),                 // 10: lt_ml_server.AnalyzedSentence
	(*AnalyzedTokenReadings)(nil),            // 11: lt_ml_server.AnalyzedTokenReadings
	(*AnalyzedToken)(nil),                    // 12: lt_ml_server.AnalyzedToken
	(*PostProcessingRequest)(nil),            // 13: lt_ml_server.PostProcessingRequest
	(*MatchRequest)(nil),                     // 14: lt_ml_server.MatchRequest
	(*MatchResponse)(nil),                    // 15: lt_ml_server.MatchResponse
	(*MatchList)(nil),                        // 16: lt_ml_server.MatchList
	(*Match)(nil),                            // 17: lt_ml_server.Match
	(*Rule)(nil),                             // 18: lt_ml_server.Rule
	(*RuleCategory)(nil),                     // 19: lt_ml_server.RuleCategory
	(*SuggestedReplacement)(nil),             // 20: lt_ml_server.SuggestedReplacement
}
var file_ml_server_proto_depIdxs = []int32{
	5,  // 0: lt_ml_server.AnalyzeRequest.options:type_name -> lt_ml_server.ProcessingOptions
	0,  // 1: lt_ml_server.ProcessingOptions.level:type_name -> lt_ml_server.ProcessingOptions.Level
	10, // 2: lt_ml_server.AnalyzeResponse.sentences:type_name -> lt_ml_server.AnalyzedSentence
	10, // 3: lt_ml_server.ProcessRequest.sentences:type_name -> lt_ml_server.AnalyzedSentence
	5,  // 4: lt_ml_server.ProcessRequest.options:type_name -> lt_ml_server.ProcessingOptions
	17, // 5: lt_ml_server.ProcessResponse.rawMatches:type_name -> lt_ml_server.Match
	17, // 6: lt_ml_server.ProcessResponse.matches:type_name -> lt_ml_server.Match
	10, // 7: lt_ml_server.AnalyzedMatchRequest.sentences:type_name -> lt_ml_server.AnalyzedSentence
	11, // 8: lt_ml_server.AnalyzedSentence.tokens:type_name -> lt_ml_server.AnalyzedTokenReadings
	12, // 9: lt_ml_server.AnalyzedTokenReadings.readings:type_name -> lt_ml_server.AnalyzedToken
	16, // 10: lt_ml_server.PostProcessingRequest.matches:type_name -> lt_ml_server.MatchList
	16, // 11: lt_ml_server.MatchResponse.sentenceMatches:type_name -> lt_ml_server.MatchList
	17, // 12: lt_ml_server.MatchList.matches:type_name -> lt_ml_server.Match
	20, // 13: lt_ml_server.Match.suggestedReplacements:type_name -> lt_ml_server.SuggestedReplacement
	1,  // 14: lt_ml_server.Match.type:type_name -> lt_ml_server.Match.MatchType
	18, // 15: lt_ml_server.Match.rule:type_name -> lt_ml_server.Rule
	19, // 16: lt_ml_server.Rule.category:type_name -> lt_ml_server.RuleCategory
	2,  // 17: lt_ml_server.Rule.tags:type_name -> lt_ml_server.Rule.Tag
	3,  // 18: lt_ml_server.SuggestedReplacement.type:type_name -> lt_ml_server.SuggestedReplacement.SuggestionType
	4,  // 19: lt_ml_server.ProcessingServer.Analyze:input_type -> lt_ml_server.AnalyzeRequest
	7,  // 20: lt_ml_server.ProcessingServer.Process:input_type -> lt_ml_server.ProcessRequest
	14, // 21: lt_ml_server.MLServer.Match:input_type -> lt_ml_server.MatchRequest
	9,  // 22: lt_ml_server.MLServer.MatchAnalyzed:input_type -> lt_ml_server.AnalyzedMatchRequest
	13, // 23: lt_ml_server.PostProcessingServer.Process:input_type -> lt_ml_server.PostProcessingRequest
	6,  // 24: lt_ml_server.ProcessingServer.Analyze:output_type -> lt_ml_server.AnalyzeResponse
	8,  // 25: lt_ml_server.ProcessingServer.Process:output_type -> lt_ml_server.ProcessResponse
	15, // 26: lt_ml_server.MLServer.Match:output_type -> lt_ml_server.MatchResponse
	15, // 27: lt_ml_server.MLServer.MatchAnalyzed:output_type -> lt_ml_server.MatchResponse
	15, // 28: lt_ml_server.PostProcessingServer.Process:output_type -> lt_ml_server.MatchResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_ml_server_proto_init() }
func file_ml_server_proto_init() {
	if File_ml_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_server_proto_rawDesc), len(file_ml_server_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ml_server_proto_goTypes,
		DependencyIndexes: file_ml_server_proto_depIdxs,
		EnumInfos:         file_ml_server_proto_enumTypes,
		MessageInfos:      file_ml_server_proto_msgTypes,
	}.Build()
	File_ml_server_proto = out.File
	file_ml_server_proto_goTypes = nil
	file_ml_server_proto_depIdxs = nil
}
