package correction

import (
	_ "embed"
	"strings"
	"sync"
)

// dialectLexiconBritish is the VarCon-derived (American -> British) wordlist
// shipped in-tree. The builder bridge/scripts/build-dialect-lexicon.sh
// regenerates this file at maintainer-developer time; the runtime path
// never reads it from disk — the bytes below are parsed lazily on the
// first BritishLexicon() call and cached via sync.Once. Pinning the source
// archive and its SHA-256 inside the script keeps the embedded payload
// reproducible across rebuilds and is the only thing that prevents this
// file from drifting between deploys.
//
//go:embed dialect_lexicon_british.txt
var dialectLexiconBritish []byte

var (
	britishLexiconOnce   sync.Once
	britishLexiconCached map[string]string
)

// BritishLexicon returns the embedded American -> British spellings as a
// lowercase-keyed map. Keys are single ASCII alphabetic tokens; values
// likewise. The first call parses the embedded TSV into a map; subsequent
// calls reuse the parsed snapshot.
//
// Construction is on-demand: deploys that never call this (e.g. when
// GF_DIALECT_SPELLING_GUARD is off, or when the harbor deploy is American)
// never pay the parse cost — the embed bytes are not parsed at startup,
// and the caller in E3 is expected to gate the construction itself on
// the british dialect config before invoking NewDialectSpellingRepair.
func BritishLexicon() map[string]string {
	britishLexiconOnce.Do(parseBritishLexicon)
	return britishLexiconCached
}

// parseBritishLexicon parses the embedded TSV into britishLexiconCached.
// TSV format: one "american\tbritish" pair per line, sorted by american
// ascending. Lines starting with '#' or that fail the cleanliness check
// are skipped — the embedded payload is regenerated by the build script
// so defensive parsing is overkill there, but it keeps a hand-edited file
// (which we never expect) from crashing the bridge on startup.
func parseBritishLexicon() {
	lexicon := make(map[string]string)
	for _, raw := range strings.Split(string(dialectLexiconBritish), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		us, gb, ok := strings.Cut(line, "\t")
		if !ok {
			continue
		}
		us = strings.ToLower(strings.TrimSpace(us))
		gb = strings.ToLower(strings.TrimSpace(gb))
		if us == "" || gb == "" || us == gb {
			continue
		}
		lexicon[us] = gb
	}
	britishLexiconCached = lexicon
}
